plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.csl.macrologandroid'
    compileSdk 34

    defaultConfig {
        applicationId "com.csl.macrolog"
        minSdk 34
        targetSdk 34
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "SERVER_URL", "\"https://macrolog-backend.herokuapp.com/\""
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release {
            minifyEnabled false
            buildConfigField 'String', 'SERVER_URL', '"https://macrolog-backend.herokuapp.com/"'
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    buildFeatures {
        viewBinding true
    }
}

dependencies {
    def room_version = "2.6.1"
    implementation libs.appcompat
    implementation libs.material
    implementation libs.constraintlayout
    implementation libs.lifecycle.livedata.ktx
    implementation libs.lifecycle.viewmodel.ktx
    implementation libs.navigation.fragment
    implementation libs.navigation.ui
    implementation libs.room.runtime
    implementation libs.room.rxjava3
    implementation libs.retrofit
    implementation libs.converter.gson
    implementation libs.adapter.rxjava3
    implementation libs.rxJava3
    implementation libs.rxAndroid
    implementation libs.okhttp

    compileOnly libs.lombok

    annotationProcessor libs.lombok
    annotationProcessor "androidx.room:room-compiler:$room_version"

    testImplementation libs.junit
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}